In [1]:
import tensorflow as tf
from tensorflow.keras.preprocessing import image
import numpy as np
import urllib
import cv2
import pathlib

In [2]:
model = tf.keras.models.load_model("drive/My Drive/TIES4911/task4/task4-3/model")

In [3]:
img_path = 'https://storage.googleapis.com/kagglesdsdata/datasets/481068/909724/black_dress/06130b80c92914dcccb56634594b4aeab7db5944.jpg?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=databundle-worker-v2%40kaggle-161607.iam.gserviceaccount.com%2F20230228%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20230228T215322Z&X-Goog-Expires=345600&X-Goog-SignedHeaders=host&X-Goog-Signature=18ed011f1e234b3272a4ee9a0eab060869536ecc1636fe2c92debb07c5346f4c7047224347d157c142485b95d205f2394d3a4dcd144e4e9569074d025f775a072e05bc2d5078dc8a31bc182a39c463f2b892dc2220160b736c423b6d18a4a903cbb7a16bec404b17e90fb21b75a695ed0f34bf6efbb2cde694673d7bbf9e351df6a8d7ecdc76016f0681a7793ad89c9e020f79904e52440f580bfbe49ce9d6a9d2664992870039461f5d11babe25b092d244df601a9c4674563a4e0b97bd2974b0e44fad15805673ec42d6a78fc6071576ea92a2e61f92013fb1e9c694651c14d0e4e50ee7604cb78c330b25e12283d917dcb434b8d6682970de2a79610649a4'
x = urllib.request.urlopen(img_path)
x = np.asarray(bytearray(x.read()), dtype="uint8")
x = cv2.imdecode(x, cv2.IMREAD_COLOR)
x = cv2.resize(x, (224, 224))
x = np.expand_dims(x, axis=0).astype(np.float32)

In [ ]:
pred = model.predict(x)

1/1 [==============================] - 0s 65ms/step


In [ ]:
print(pred)
print(np.argmax(pred))

[[0.13026868 0.09111526 0.16387253 0.04936486 0.02643572 0.06370683
  0.04571718 0.06311819 0.02108636 0.01405967 0.03867988 0.0177963
  0.00640663 0.03106719 0.02773143 0.01978883 0.00886466 0.03481705
  0.0177426  0.02184219 0.05131989 0.02499961 0.02148725 0.00871119]]
2


In [4]:
data_dir = pathlib.Path('drive/My Drive/TIES4911/task4/apparel-images-dataset')
image_count = len(list(data_dir.glob('*/*.jpg')))
print(image_count)

11385


In [5]:
batch_size = 32
img_height = 224
img_width = 224

In [18]:
(train_ds, val_ds) = tf.keras.utils.image_dataset_from_directory(
    data_dir,
    shuffle=False,
    validation_split=0.2,
    subset='both',
    image_size=(img_height, img_width),
    batch_size=batch_size,
    seed=123,
    label_mode='categorical'
)

Found 11385 files belonging to 24 classes.
Using 9108 files for training.
Using 2277 files for validation.


In [7]:
AUTOTUNE = tf.data.AUTOTUNE

train_ds = train_ds.cache().shuffle(1000).prefetch(buffer_size=AUTOTUNE)
val_ds = val_ds.cache().prefetch(buffer_size=AUTOTUNE)

In [23]:
for x, y in train_ds.take(1):
  print(x[0][0])
  print(y)
print(train_ds.class_names)
print(train_ds.labels)

tf.Tensor(
[[2.62552810e+00 1.06749249e+00 1.62552822e+00]
 [1.13198442e+01 9.31984425e+00 1.03198442e+01]
 [2.06737185e+00 8.57550561e-01 1.06737185e+00]
 [5.45235777e+00 3.54610777e+00 4.45235777e+00]
 [8.80774784e+00 6.80774784e+00 7.80774784e+00]
 [1.64151802e+01 1.44151802e+01 1.54151802e+01]
 [1.36449213e+01 1.16449213e+01 1.26449213e+01]
 [2.14386392e+00 7.73328185e-01 1.14386404e+00]
 [1.00000000e+00 0.00000000e+00 0.00000000e+00]
 [8.77344704e+00 6.77344656e+00 7.77344656e+00]
 [4.12500000e+00 2.12500000e+00 3.12500000e+00]
 [3.89311647e+00 1.89311647e+00 2.89311647e+00]
 [1.27699013e+01 1.07699013e+01 1.17699013e+01]
 [8.42770863e+00 6.42770863e+00 7.42770863e+00]
 [1.97072830e+01 1.78903198e+01 1.83412094e+01]
 [1.05877972e+01 9.58779716e+00 7.58779716e+00]
 [1.41518021e+00 4.15180206e-01 0.00000000e+00]
 [2.10296459e+01 2.00296459e+01 1.60296459e+01]
 [1.48822250e+01 1.38822250e+01 9.88222504e+00]
 [1.34425759e+00 3.44257593e-01 0.00000000e+00]
 [1.48051252e+01 1.38051252e+

AttributeError: ignored